name: Install SGX SDK
description: Installs the Intel SGX SDK (and propagates environment variables)

runs:
  using: composite
  steps:
    - name: Install SGX SDK
      shell: bash
      # In order to propagate teh environment variables to subsequent steps we
      # need to redirect through $GITHUB_ENV, see
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      # We can't do `cat /opt/intel/sgxsdk/environment >> $GITHUB_ENV` because
      # the environment file has _logic_ which the `GITHUB_ENV` parser will
      # fail on.  So we manually pass on the known environment variables.
      run:
        source /etc/lsb-release &&
        wget "https://download.01.org/intel-sgx/sgx-linux/2.17/distro/ubuntu${DISTRIB_RELEASE}-server/sgx_linux_x64_sdk_2.17.100.3.bin" &&
        chmod +x ./sgx_linux_x64_sdk_2.17.100.3.bin &&
        ./sgx_linux_x64_sdk_2.17.100.3.bin --prefix=/opt/intel &&
        source /opt/intel/sgxsdk/environment &&
        echo "SGX_SDK=$SGX_SDK" >> $GITHUB_ENV &&
        echo "PATH=$PATH" >> $GITHUB_ENV &&
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV &&
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV

